// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk0v8AVX22sKKaZhQ5YtxDcaiaFvNMgzA',
    appId: '1:288213646969:web:70055cc31a3ca79aebdea8',
    messagingSenderId: '288213646969',
    projectId: 'flutter-notification-1fedb',
    authDomain: 'flutter-notification-1fedb.firebaseapp.com',
    storageBucket: 'flutter-notification-1fedb.appspot.com',
    measurementId: 'G-SYBEG7Y51W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbEDbBHCUA-KFqCIpJitl_af3lHY1UiOc',
    appId: '1:288213646969:android:0bfa1e4dbef92705ebdea8',
    messagingSenderId: '288213646969',
    projectId: 'flutter-notification-1fedb',
    storageBucket: 'flutter-notification-1fedb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDf7EFx0N0CQs-zyq1pAmvK8CnK1Vi2KMY',
    appId: '1:288213646969:ios:6e4987943324bec2ebdea8',
    messagingSenderId: '288213646969',
    projectId: 'flutter-notification-1fedb',
    storageBucket: 'flutter-notification-1fedb.appspot.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDf7EFx0N0CQs-zyq1pAmvK8CnK1Vi2KMY',
    appId: '1:288213646969:ios:6e4987943324bec2ebdea8',
    messagingSenderId: '288213646969',
    projectId: 'flutter-notification-1fedb',
    storageBucket: 'flutter-notification-1fedb.appspot.com',
    iosBundleId: 'com.example.firebaseNotification',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDk0v8AVX22sKKaZhQ5YtxDcaiaFvNMgzA',
    appId: '1:288213646969:web:1ed73bad08282192ebdea8',
    messagingSenderId: '288213646969',
    projectId: 'flutter-notification-1fedb',
    authDomain: 'flutter-notification-1fedb.firebaseapp.com',
    storageBucket: 'flutter-notification-1fedb.appspot.com',
    measurementId: 'G-KE8967Z1BE',
  );
}
